# Convolutional Neural Network

### Importing the libraries

In [1]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

In [2]:
tf.__version__

'2.12.0-rc1'

## Part 1 - Data Preprocessing

### Preprocessing the Training set

In [30]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 8000 images belonging to 2 classes.


In [31]:
train_datagen1 = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
trainingSet = train_datagen1.flow_from_directory('dataset/train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 350 images belonging to 5 classes.


### Preprocessing the Test set

In [32]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 2000 images belonging to 2 classes.


In [33]:
test_datagen1 = ImageDataGenerator(rescale = 1./255)
testSet = test_datagen1.flow_from_directory('dataset/test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 50 images belonging to 5 classes.


## Part 2 - Building the CNN

### Initialising the CNN

In [55]:
cnn = tf.keras.models.Sequential()
cnn2 = tf.keras.models.Sequential()

### Step 1 - Convolution

In [56]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))
cnn2.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

### Step 2 - Pooling

In [57]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn2.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Adding a second convolutional layer

In [58]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

cnn2.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn2.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Step 3 - Flattening

In [59]:
cnn.add(tf.keras.layers.Flatten())
cnn2.add(tf.keras.layers.Flatten())

### Step 4 - Full Connection

In [60]:
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn2.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Step 5 - Output Layer

In [40]:
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [61]:
cnn2.add(tf.keras.layers.Dense(units=5, activation='softmax'))

## Part 3 - Training the CNN

### Compiling the CNN

In [62]:
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn2.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the CNN on the Training set and evaluating it on the Test set

In [43]:
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

Epoch 1/25
250/250 [==============================] - 47s 185ms/step - loss: 0.6676 - accuracy: 0.5981 - val_loss: 0.6183 - val_accuracy: 0.6630
Epoch 2/25
250/250 [==============================] - 27s 109ms/step - loss: 0.6012 - accuracy: 0.6761 - val_loss: 0.5627 - val_accuracy: 0.7190
Epoch 3/25
250/250 [==============================] - 30s 120ms/step - loss: 0.5488 - accuracy: 0.7203 - val_loss: 0.5247 - val_accuracy: 0.7460
Epoch 4/25
250/250 [==============================] - 30s 120ms/step - loss: 0.5161 - accuracy: 0.7504 - val_loss: 0.4955 - val_accuracy: 0.7645
Epoch 5/25
250/250 [==============================] - 27s 107ms/step - loss: 0.5008 - accuracy: 0.7582 - val_loss: 0.4937 - val_accuracy: 0.7710
Epoch 6/25
250/250 [==============================] - 25s 100ms/step - loss: 0.4666 - accuracy: 0.7765 - val_loss: 0.4819 - val_accuracy: 0.7785
Epoch 7/25
250/250 [==============================] - 25s 98ms/step - loss: 0.4553 - accuracy: 0.7851 - val_loss: 0.5167 - val_acc

In [63]:
cnn2.fit(x = trainingSet, validation_data = testSet, epochs = 20)

Epoch 1/20
11/11 [==============================] - 3s 263ms/step - loss: 1.6462 - accuracy: 0.2514 - val_loss: 1.5459 - val_accuracy: 0.1800
Epoch 2/20
11/11 [==============================] - 3s 222ms/step - loss: 1.4201 - accuracy: 0.3057 - val_loss: 1.3241 - val_accuracy: 0.4400
Epoch 3/20
11/11 [==============================] - 3s 242ms/step - loss: 1.2951 - accuracy: 0.4057 - val_loss: 1.2101 - val_accuracy: 0.4800
Epoch 4/20
11/11 [==============================] - 3s 226ms/step - loss: 1.2260 - accuracy: 0.4657 - val_loss: 1.1428 - val_accuracy: 0.5000
Epoch 5/20
11/11 [==============================] - 3s 220ms/step - loss: 1.1525 - accuracy: 0.5143 - val_loss: 1.1025 - val_accuracy: 0.5400
Epoch 6/20
11/11 [==============================] - 3s 212ms/step - loss: 1.1954 - accuracy: 0.5114 - val_loss: 1.1924 - val_accuracy: 0.4000
Epoch 7/20
11/11 [==============================] - 3s 243ms/step - loss: 1.1513 - accuracy: 0.4771 - val_loss: 1.0413 - val_accuracy: 0.6000
Epoch 

## Part 4 - Making a single prediction

In [50]:
import numpy as np
from keras.preprocessing import image
test_image = tf.keras.utils.load_img('dataset/single_prediction/cat_or_dog_1.jpg', target_size = (64, 64))
test_image = tf.keras.utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
  prediction = 'dog'
else:
  prediction = 'cat'

1/1 [==============================] - 1s 505ms/step


In [51]:
print(prediction)

dog


In [64]:
train_metrics = cnn2.evaluate(trainingSet)
test_metrics = cnn2.evaluate(testSet)

print("Training Metrics:", train_metrics)
print("Validation Metrics:", test_metrics)

2/2 [==============================] - 0s 32ms/step - loss: 0.6652 - accuracy: 0.7400
Training Metrics: [0.4908389747142792, 0.8285714387893677]
Validation Metrics: [0.6652107834815979, 0.7400000095367432]


In [70]:
# from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Load the image
image = tf.keras.utils.load_img("dataset/testing/fire2.jpeg", target_size=(64, 64))  # Adjust the target size to match your model's input size

# Convert the image to a numpy array and normalize it
image_array = tf.keras.utils.img_to_array(image)
image_array = image_array / 255.0  # Normalize the pixel values to [0, 1]

# Reshape the image array to match the expected input shape of your model
image_array = np.expand_dims(image_array, axis=0)

In [71]:
predictions = cnn2.predict(image_array)

1/1 [==============================] - 0s 16ms/step


In [72]:
predicted_class_index = np.argmax(predictions, axis=1)

In [73]:
print(predicted_class_index)

[2]


In [ ]:
class_labels = ['Combat', 'DestroyedBuildings', 'Fire', 'HumanitarianAid', 'Military']
predicted_class_label = class_labels[predicted_class_index[0]]

In [74]:
import os

folder_path = "dataset/testing"
image_files = [f for f in os.listdir(folder_path) if f.endswith(('.jpg', '.jpeg', '.png', '.gif'))]

In [76]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

predictions = []

for image_file in image_files:
    # Load and preprocess the image
    image_path = os.path.join(folder_path, image_file)
    image = load_img(image_path, target_size=(64, 64))  # Adjust the target size to match your model's input size
    image_array = img_to_array(image)
    image_array = image_array / 255.0  # Normalize the pixel values to [0, 1]
    image_array = np.expand_dims(image_array, axis=0)

    # Make predictions
    predictions_for_image = cnn2.predict(image_array)

    # Store the predictions and the corresponding image file name
    predictions.append((image_file, predictions_for_image))

1/1 [==============================] - 0s 17ms/step


In [82]:
predictions

[('building1.jpeg',
  array([[5.5328286e-03, 9.8950374e-01, 3.2577573e-03, 1.4267617e-03,
          2.7889039e-04]], dtype=float32)),
 ('building2.jpeg',
  array([[0.0305383 , 0.70732254, 0.01465762, 0.24543883, 0.00204285]],
        dtype=float32)),
 ('combat1.jpeg',
  array([[0.3727727 , 0.22813998, 0.00266462, 0.38300934, 0.01341338]],
        dtype=float32)),
 ('combat2.jpeg',
  array([[0.75023454, 0.03939456, 0.00075613, 0.20870428, 0.00091052]],
        dtype=float32)),
 ('fire1.jpeg',
  array([[9.2198587e-09, 3.6345469e-08, 9.9672592e-01, 3.2740701e-03,
          6.9400603e-15]], dtype=float32)),
 ('fire2.jpeg',
  array([[1.1693233e-23, 4.9440242e-36, 1.0000000e+00, 1.3028020e-14,
          0.0000000e+00]], dtype=float32)),
 ('military1.jpeg',
  array([[0.4022992 , 0.42897835, 0.00258328, 0.01901155, 0.1471276 ]],
        dtype=float32)),
 ('military2.jpeg',
  array([[1.2988360e-01, 1.7533476e-03, 4.5239613e-05, 4.2303256e-03,
          8.6408746e-01]], dtype=float32)),
 ('rehab